package com.example.iamsystem.audit.enums;

public enum AuditEventType {
    // Authentication
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    TOKEN_REFRESH_SUCCESS,
    TOKEN_REFRESH_FAILURE,

    // User Management
    USER_REGISTERED,
    USER_REGISTRATION_FAILED,
    PASSWORD_CHANGE_SUCCESS,
    PASSWORD_CHANGE_FAILURE,
    PASSWORD_UPDATED,
    PASSWORD_UPDATE_FAILED,
    ROLES_ASSIGNED,
    ROLES_ASSIGNMENT_FAILED,
    ROLES_REMOVED,
    ROLES_REMOVAL_FAILED,
    USER_DELETED,
    USER_DELETION_FAILED,

    // Role Management
    ROLE_CREATED,
    ROLE_CREATION_FAILED,
    ROLE_UPDATED,
    ROLE_UPDATE_FAILED,
    ROLE_DELETED,
    ROLE_DELETION_FAILED,
    PERMISSIONS_ASSIGNED_TO_ROLE,
    PERMISSIONS_ASSIGNMENT_TO_ROLE_FAILED,
    PERMISSIONS_REMOVED_FROM_ROLE,
    PERMISSIONS_REMOVAL_FROM_ROLE_FAILED,

    // Permission Management
    PERMISSION_CREATED,
    PERMISSION_CREATION_FAILED,
    PERMISSION_UPDATED,
    PERMISSION_UPDATE_FAILED,
    PERMISSION_DELETED,
    PERMISSION_DELETION_FAILED,
    PERMISSIONS_REMOVED_FROM_ROLE_FAILED,

    // Password Reset
    PASSWORD_RESET_OTP_REQUESTED,
    PASSWORD_RESET_OTP_REQUEST_FAILED,
    PASSWORD_RESET_SUCCESS,
    PASSWORD_RESET_FAILURE
}